# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa83b7c634a3be4baadc6c658b80917cd89965e3c19c95d359e4a69f108ea77a8ea42ffe1060460b2bb6d3576842d9619679dfd748f03604252da959bd70e4c

test:
  secret_key_base: 5f214c2bfda9abe4870ee0e84489808c9033b6d828760d10c49771fb6308439308f17ff5eda16ace09fe14784a5650cd9faa738b2b02cf45583a8f726e8444ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
